### ISSUE TITLE
Several usage of the same target in procfile: doc update or code to warn user

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/documentation#1003]
Ex:

`
web: blabla
web: hello
`

Only "hello" will be executed when some users are expecting "blabla" then "hello"

**Comment by johnsudaar** [comment]
The code is in the appsdeck-builder project. (In a script named: app-starter.sh which use a library called procfile_d.lib.sh).
You could use something like that:

```
cat Procfile | cut -d ':' -f 1 | sort | uniq -d
``` 
To find duplicated entries.
