### ISSUE TITLE
[PHP] IP Filtering page does not work on symfony

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#1042]
It fails with:
```
nginx: [emerg] duplicate location "/" in /app/nginx-ips-filtering.conf:1
```

**Comment by EtienneM** [comment]
I just tried to apply the content of the page https://doc.scalingo.com/languages/php/ips-filtering on our Symfony sample (https://php-symfony.is-easy-on-scalingo.com/) and didn't faced any issue. It may have been true in the past but it does not seem to still apply. Feel free to re-open with an example which reproduces the issue if you think I got it wrong.
