### ISSUE TITLE
Several important are missing from the Logs page 

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#1061]
- explanation of cold and hot logs
- policy regarding hot logs becoming cold logs
- logs storage policy

**Comment by yannski** [comment]
- a warning message that logs streaming in the dashboard is not that useful when the logs flow is important?
- mention that Logs can be complemented by Log Drains (and link the page)

**Comment by yannski** [comment]
- it needs a proper introduction: what are logs? Whats is Scalingo responsability? What is the application's developer responsability (stdout, etc)? Explain the difference between cold and hot logs in the introduction.

**Comment by EtienneM** [comment]
Are you talking about this page: https://doc.scalingo.com/platform/app/logs?

**Comment by yannski** [comment]
> Are you talking about this page: https://doc.scalingo.com/platform/app/logs?

Yes

**Comment by yannski** [comment]
- in the sidebar the "Log Drains" entry should appear below the "Logs" entry
