### ISSUE TITLE
[logs-archive] Document retention time

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#1084]
We keep logs-archive for one year

**Comment by EtienneM** [comment]
The section "Logs Archive" (https://doc.scalingo.com/platform/app/logs#logs-archives) mentions:

> All your logs are archived by Scalingo for one year

Did you think about adding more about it or is it enough?

**Comment by Soulou** [comment]
It's not enough, there should be a title "Log Retention"
