### ISSUE TITLE
[PHP] Example of nginx configuration for common actions should be present

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#1105]
https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/unassigned/conversations/12375700010694

**Comment by EtienneM** [comment]
We already have a few pages about Nginx configuration for PHP apps such as https://doc.scalingo.com/languages/php/basic-auth and https://doc.scalingo.com/languages/php/ips-filtering. I don't really understand the specific of this issue 🤔

**Comment by EtienneM** [comment]
Ping @Soulou if you have more examples about what you want here.

**Comment by Soulou** [comment]
All the support tickets related to nginx configuration should be present here, from my head:

* IP filtering
* Additional PHP entrypoint for a Symfony app
* Additional PHP entrypoint for a Laravel app (case of the support linked in the issue)
* Configure proxying by path: `/api` → proxy to `api.my-app.com`, and the rest on `front.my-app.com` (Using ERB templating and env vars)

If we've those 4 it's already some support tickets we can answer :-)
