### ISSUE TITLE
Add scheduled jobs sample page based on other languages like Python

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#113]
BackgroundScheduler can be used.

**Comment by EtienneM** [comment]
We have Ruby and PHP here: https://doc.scalingo.com/platform/app/run-scheduled-tasks#example

**Comment by raphodn** [comment]
There's many examples, but none for Python (Django for instance). Does it mean it's not possible ?

**Comment by EtienneM** [comment]
In Python, Celery (https://pypi.org/project/celery/) is a famous dependency to handle tasks queue. There is a documentation page about it: https://doc.scalingo.com/languages/python/celery-flask

There is also a sample deployed (https://python-celery.is-easy-on-scalingo.com/), with the code available (https://github.com/Scalingo/sample-python-celery).
