### ISSUE TITLE
Importing a collection

### ISSUE THREAD

**Issue by olmaga** [Scalingo/documentation#118]
I can't really explain it either:

We have multiple collections, we import them (exported with mongoexport) from json files. 5 of our 6 collections can be imported easily - but with one we have on all different systems (differnet local, test (mLab sandbox)) the same error:

Couldn't import documents: Performing another operation at this moment.

But it isn't. We even restarted the databases

Any idea?

**Comment by ndimas** [comment]
+1

**Comment by yannski** [comment]
It would me much simpler to come through the support chat inside the dashboard instead of entering ticker here for such matters, so we can share private infos. Thanks.
