### ISSUE TITLE
[scalingo network]: a dedicated page explaining how containers are compartmentalized

### ISSUE THREAD

**Issue by curzolapierre** [Scalingo/documentation#1226]
## Expected:

- How the containers are connected to each other
- Region limitation
- Answer to this type of question "Is it possible to limit the access to my database from other applications"

Related intercom conversation: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700025236

**Comment by EtienneM** [comment]
@curzolapierre we have a task to write a documentation page in the context of private networks. I suggest to close this issue as this is the kind of thing that will be answered in this future page.

**Comment by curzolapierre** [comment]
Yes, it makes totally sense to close this issue
