### ISSUE TITLE
Incorrect curl example in source documentation

### ISSUE THREAD

**Issue by Intrepidd** [Scalingo/documentation#1267]
From : https://developers.scalingo.com/sources

> The upload_url is designed to be used in a PUT HTTP Request:

```
curl -L -X PUT --upload-file ./archive.tar.gz 'https://$SCALINGO_API_URL/v1/sources/123e4567-e89b-12d3-a456-426655440000?token=dc958153c3cd32659ffad5deeda9405d'
```

If you do exactly this, the deploy will fail with : `Fail to fetch source code: The provided url does not point at a supported Content-Type (binary/octet-stream)`

Solution : add a content-type header to the previous curl command : `-H "Content-Type: application/x-gzip"`

This should either be present on the documentation, or the deploy should work without it :) 

Thanks !

**Comment by johnsudaar** [comment]
Thanks a lot for the repport ! 

It's now fixed by https://github.com/Scalingo/developers-documentation/pull/139
