### ISSUE TITLE
[Git] Only git clients using protocol 2 is supported to push on Scalingo git servers

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/documentation#1347]
We only support `version 2` of the git protocol.

If the git client used is less than version `2.18`, using git on Scalingo will not work because it use protocol version 1.

Specify that the customer must use at least version `2.18` which allows to use the version 2 protocol by manually defining it with:
```shell
git config --global protocol.version 2
```

Or simply update the git client to a more recent version. Git versions greater than or equal to `2.29` will use the version 2 of the protocol by default.

Sources:
- https://opensource.googleblog.com/2018/05/introducing-git-protocol-version-2.html
- https://stackoverflow.com/questions/53207973/fatal-unknown-value-for-config-protocol-version-2

**Comment by EtienneM** [comment]
As we failed to reproduce the issue, I'm closing it. Feel free to reopen with more details on how to reproduce the problem so that we can explain the solution in the documentation.
