### ISSUE TITLE
 {java.net.ConnectException: Connection refused: connect}}]

### ISSUE THREAD

**Issue by Muthukumars1994** [Scalingo/documentation#136]
I am trying to connect my mongodb server from the local 
but every thing is working fine in the server console of the mongod
I am using to access form the local to server 
It throws this below exception
Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=139.59.25.20:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by

 {java.net.ConnectException: Connection refused: connect}}]

**Comment by yannski** [comment]
Hi,
Please use the support chat for this kind of inquiry. The GitHub Issues are for issue related to the documentation. And BTW, your problem is referenced here: http://doc.scalingo.com/databases/access-database.html
