### ISSUE TITLE
[Nginx Proxy] We should add the proxy_redirect parameters in the sample configuration

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/documentation#1408]
A customer had problems with the proxy configuration. Nginx was returning an URL with the port which was the port of the Nginx proxy. The URL should not include the port as it's not work.

Related to this Nginx documentation: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect

## Problem

```shell
$ curl -v https://my-proxy-app.osc-fr1.scalingo.io/test
...
< location: http://my-proxy-app.osc-fr1.scalingo.io:23921/test/bla/bla
... 
```

## Resolution

```
location /test {
   proxy_pass https://my-app.osc-fr1.scalingo.io/test;
   proxy_redirect https://my-app.osc-fr1.scalingo.io/test https://my-proxy-app.osc-fr1.scalingo.io/test;
}
```

https://doc.scalingo.com/platform/deployment/buildpacks/nginx#configuration-examples

**Comment by EtienneM** [comment]
@brandon-welsch I don't really understand what you want to add to the doc. If you already have an example, can you provide it?

**Comment by brandon-welsch** [comment]
@EtienneM Is it better now ?
