### ISSUE TITLE
[WAR] What are autonomous JAR?

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#1413]
This page  (https://doc.scalingo.com/platform/deployment/deploy-java-jar-war) states that we can deploy JAR with the `deploy` command:

> also for autonomous JAR

But I don't get what an autonomous JAR is? I am in favor of removing this mention as it's really confusing. The provided command does not work anyway for JAR archive.

**Comment by Soulou** [comment]
Autonomous jar is a jar containing everything (tomcat application server + application usually) that you can start with `java -jar file.jar` and all the dependencies are inside

**Comment by EtienneM** [comment]
OK then I think we don't support such JAR out of the box, I don't see anything in the buildpack about that

**Comment by EtienneM** [comment]
Instructions to deploy a JAR:

Currently, Scalingo only provide an automatic deployment of WAR files.

If you need to deploy a JAR, we will also need a Procfile [1] to let us know how to start your jar.

You will have to use the jvm-common buildpack [2] [3].

To do so, the best solution is to create a tar.gz file with the following content:

```
master/Procfile
master/myfile.jar
```

Once the tar.gz has been created, you can use our cli to deploy your tar.gz with:

```
scalingo --region [REGION_NAME] --app [APP_NAME] deploy archive.tar.gz
```

[1] https://doc.scalingo.com/platform/app/procfile#top-of-page

[2] https://github.com/Scalingo/buildpack-jvm-common

[3] https://doc.scalingo.com/platform/deployment/buildpacks/custom#top-of-page
