### ISSUE TITLE
Tour link's doesn't work

### ISSUE THREAD

**Issue by MrMourse** [Scalingo/documentation#142]
When i'm on http://doc.scalingo.com/ and I click on Tour, I'm redirected to a blank page : https://scalingo.com/tour

**Comment by yannski** [comment]
Hide the link to the Tour (which does not exist ATM)

**Comment by MrMourse** [comment]
Done.

**Comment by MrMourse** [comment]
Oh may be miss understand I remove the print of "Tour" but you want may be keep it and just cancel the link to it ?
