### ISSUE TITLE
[MongoDB Compass] SSL may need to be set to "Unvalidated (insecure)"

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#1477]
A customer reported that he received an error `self signed certificate in certificate chain` when attempting to use MongoDB Compass to open a DB tunnel and connect to his database. 

It eventually succeeded to connect by setting SSL to `Unvalidated (insecure)`.

On my side, I didn't need this parameter to make it work.

https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700053331

**Comment by Soulou** [comment]
@EtienneM have you added our CA to your local chain? Because what the customer reported seems "normal" to me.

**Comment by EtienneM** [comment]
I checked with the following command and it does not look like I added it. The following command returns nothing:

```bash
awk -v cmd='openssl x509 -noout -subject' ' /BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt | grep Scalingo
```
