### ISSUE TITLE
[Scalingo Scheduler] Mention the timezone for the cron expression is in UTC

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#1484]
https://doc.scalingo.com/platform/app/task-scheduling/scalingo-scheduler

**Comment by yannski** [comment]
+ give real word examples on how to take this into account in real world scenario (for example when you're in the timezones of London/Lisbon, Paris/Berlin and Athene)

**Comment by EtienneM** [comment]
This issue is needed for the public beta release of the product. It will be handled in the next ninja sprint.
