### ISSUE TITLE
[nginx] Create a "Getting Started" guide to deploy a WAF with ModSecurity

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#1615]
Everything is explained in the buildpack README: https://github.com/Scalingo/nginx-buildpack/#using-nginx-as-waf-with-modsecurity

**Comment by Frzk** [comment]
Considering the NGINX has announced several months ago that NGINX WAF is transitioning to EOL (see https://www.nginx.com/blog/f5-nginx-modsecurity-waf-transitioning-to-eol), is this still wanted?

**Comment by EtienneM** [comment]
> Considering the NGINX has announced several months ago that NGINX WAF is transitioning to EOL (see https://www.nginx.com/blog/f5-nginx-modsecurity-waf-transitioning-to-eol), is this still wanted?

Yes it is. We recently implemented this in our Nginx Buildpack so it should be documented. Moreover EOL is planned for 2024. Having it for 2 more years is enough to justify the need for the documentation here IMO
