### ISSUE TITLE
[How to migrate from Heroku] Remove reference to heroku2scalingo

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/documentation#1621]
This page https://doc.scalingo.com/platform/getting-started/how-to-migrate-from-heroku is deprecated. We should remove it as the tool is not maintained anymore.

**Comment by btrd** [comment]
We're gonna edit the page to help user coming from heroku to do what's heroku2scalingo was doing automatically.

https://scalingo.slack.com/archives/C028YKACUUW/p1651565335425789
