### ISSUE TITLE
Present dbclient-fetcher tool

### ISSUE THREAD

**Issue by btrd** [Scalingo/documentation#1660]
We mention `dbclient-fetcher` multiple times, but we never say what it does exactly.

We could explain this tool in the One-Off page https://doc.scalingo.com/platform/app/tasks

**Comment by Frzk** [comment]
Hello @btrd,

We already have this section: [https://doc.scalingo.com/platform/databases/access#manually-install-the-databases-cli-in-one-off](https://doc.scalingo.com/platform/databases/access#manually-install-the-databases-cli-in-one-off), which is available in Platform > Databases > Access Your Database.

From my point of view it's sufficient and quite logical to find it here.

Did you have something else in mind? :)

**Comment by btrd** [comment]
Indeed that's exactly what I had in mind, but our search isn't finding this page :( gonna create a ticket to note that we should improve our search

<img width="596" alt="Capture d’écran 2022-08-08 à 11 04 08" src="https://user-images.githubusercontent.com/1385737/183381541-abc8ac60-96ce-4b2a-96b2-7ddeb6739480.png">

**Comment by Frzk** [comment]
The search engine is indeed improvable ><
