### ISSUE TITLE
[Rails] Document how to install VIPS

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#1663]
Currently Rails image processing requires VIPS to be installed, but it's not in our the list of packages of our stack. A customer did a bunch of attempts to install it, either via the APT buildpack or via a community buildpack (https://github.com/jcamblan/scalingo-buildpack-vips). Both solution works but provide a different version of VIPS. The community buildpack solution provides the latest version of VIPS. 

We should document how to install VIPS as it's an essential part of Rails app with image processing.

All the details in the Intercom conversation: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700069615

**Comment by brandon-welsch** [comment]
Another customer that want to install libvips: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/3379738/conversations/12375700071925

**Comment by btrd** [comment]
https://doc.scalingo.com/languages/ruby/rails/start#use-vips-to-process-image

I added this paragraph in our doc.

Should we add a paragraph about this buildpack too ? https://github.com/BaguetteEngineering/scalingo-buildpack-vips As the version is newer.
