### ISSUE TITLE
[Regression] The CLI documentation should be checked because of the urfave/cli v2 migration

### ISSUE THREAD

**Issue by QuentinEscudierScalingo** [Scalingo/documentation#1740]
The migration introduced by the urfave/cli v2 migration by the pr #774 changed the way commands are done.
Some example in the CLI help are now deprecated c.f.: #787

**Comment by brandon-welsch** [comment]
@QuentinEscudierScalingo Your links doesn't go to the right project. They are linked to the documentation not the CLI. Can you fix it?

**Comment by QuentinEscudierScalingo** [comment]
I'm sorry @brandon-welsch, here is the link to the pr 774 of the cli: https://github.com/Scalingo/cli/pull/774
And here is the link to the issue that show examples: https://github.com/Scalingo/cli/issues/787
