### ISSUE TITLE
DPL deployment not working with ruby 3.2.x

### ISSUE THREAD

**Issue by curzolapierre** [Scalingo/documentation#1860]
With the new release of ruby (3.2.0) https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
Some method has been removed, e.g. `Dir.exists?`, `File.exists?`.
DPL is still using one of these, here: https://github.com/travis-ci/dpl/blob/master/lib/dpl/helper/assets.rb#L19
Which make the DPL fail to use `scalingo` CLI:

```bash
➜ dpl --provider=scalingo --app=$SCALINGO_APP_NAME --api-token=$SCALINGO_API_TOKEN --region=$SCALINGO_REGION --branch=refs/heads/master
Support for deployments to Scalingo is in **alpha**. Please see [Maturity Levels](https://github.com/travis-ci/dpl/#maturity-levels) for details.
$ timeout 60 ./scalingo keys-remove dpl_tmp_key
timeout: failed to run command './scalingo': No such file or directory
Failed to remove the ssh key.
```

Waiting for the fix from dpl side, we should freeze ruby version.

**Comment by EtienneM** [comment]
@curzolapierre is there a dpl ticket we can follow?

**Comment by curzolapierre** [comment]
Yes, I've updated the description.
