### ISSUE TITLE
Replace screenshots with new updated ones

### ISSUE THREAD

**Issue by mrunichs** [Scalingo/documentation#1881]
There a lot of pages that include screenshots from the former dashboard. It would be nice to be able to update them.

For instance:
https://doc.scalingo.com/databases/influxdb/start
https://doc.scalingo.com/databases/postgresql/start
https://doc.scalingo.com/databases/mysql/start
https://doc.scalingo.com/databases/mongodb/start
https://doc.scalingo.com/databases/redis/start
https://doc.scalingo.com/databases/elasticsearch/start

![image](https://user-images.githubusercontent.com/103516012/210341701-ad3fa0c2-6e40-487f-8c30-7d7a940b2d96.png)

**Comment by btrd** [comment]
Already tracked here https://github.com/Scalingo/project-items/issues/5
