### ISSUE TITLE
Add SSH key fingerprint somewhere in the documentation

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [Scalingo/documentation#1897]
In order to allow users to properly verify SSH info they are about to put in their `known_hosts` file when interacting with scalingo servers (like when pushing some code in order to deploy an app), it could be nice to have those info somewhere in our documentation.

**Comment by aurelien-reeves-scalingo** [comment]
I am not talking about the fingerprint of the user's certificate.
But the fingerprint of our certificates.

A user did interact with Scalingo servers using `git push`. So SSH was about to add the Scalingo public key to the user's `known_hosts` file. At that point, the user wanted to make sure the fingerprint of the key that was about to be written down into its `known_hosts` file was the right one.

**Comment by EtienneM** [comment]
I could add the current fingerprint to the public documentation. But what I fear is that the fingerprint may change. I asked a question internally about how to keep in sync the public documentation and the actual fingerprint.

https://scalingo.slack.com/archives/C05UZP62YRJ/p1728394767665539

**Comment by EtienneM** [comment]
Answer from IET:

> This file is an SSH key (RSA & ed25519 format), not a cert, so there's isn't any form of expiration to worry about. More, the same file is shared between our two front server, so it's safe to write it on the doc.
> To extract the fingerprint from the host, you can use the following command: `ssh-keyscan ssh.osc-fr1.scalingo.com | ssh-keygen -lf -`

**Comment by sc-zenokerr** [comment]
Similar to Etienne's question about fingerprints changing. I asked a question along the same lines here: https://scalingo.slack.com/archives/C05UZP62YRJ/p1727422805724269
Apologies for not linking it here.
