### ISSUE TITLE
Better explain the impact of enabling Review Apps

### ISSUE THREAD

**Issue by guillaume-sc** [Scalingo/documentation#1911]
Update [Scalingo documentation about Review Apps](https://doc.scalingo.com/platform/app/review-apps) to make it more descriptive of the impacts when the feature is enabled.

### Addons, Collaborators and Environment Variables

In the [section **Addons, Collaborators and Environment Variables**](https://doc.scalingo.com/platform/app/review-apps#addons-collaborators-and-environment-variables), the documentation mentions the following:
> By default child applications will get a copy collaborators and environment variables from the parent application.
>
> Child applications also inherit the addons formation of the parent application: same addons and same addon plans.

Here, expand what a Review App inherits from its parent application regarding environment variables: API keys, database credentials, any secrets.

> This default behavior can be customized, see below.

Here, mention that the customization can allow to connect directly the Review App to the parent application database and addons, so Review Apps must be enabled only when trusted sources are allowed to create merge requests in the source code repositories. As a consequence, Scalingo prevents Review Apps from being created from forks of the original repository.

### Configuration of Review Apps

In the [section **Configuration of Review Apps**](https://doc.scalingo.com/platform/app/review-apps#configuration-of-review-apps), the documentation mentions the following:
> Having a strict copy of the parent application is sometimes not desirable. You might not want to copy production credentials, or it is sometimes required to start a custom task after the initialization of the app. That’s where the [Scalingo JSON manifest](https://doc.scalingo.com/platform/app/app-manifest) becomes useful.

Here, mention that although there are valid reasons to configure `scalingo.json` for Review Apps to connect to their parent database, and addons, this means personal, or health-related information can be exposed. As a consequence, Scalingo recommends not to enable Review Apps for production applications; the preferred approach is to create a second application linking to the same repository. This second, separate application can then have Review Apps, while protecting production data.

**Comment by benjaminach** [comment]
![Image](https://user-images.githubusercontent.com/425310/215751977-77f64fc8-88b8-4ccc-a688-8a71c302c9ef.png)
![Image](https://user-images.githubusercontent.com/425310/215751976-0e758daf-a985-4591-9097-7f13fc731603.png)

**Comment by cyrille-sg** [comment]
Implementation ticket: https://github.com/Scalingo/documentation/issues/1913
PR texts: https://github.com/Scalingo/documentation/pull/1912
PR Images: https://github.com/Scalingo/documentation/pull/1914

**Comment by yanjost** [comment]
I'd prefer a clear separation between feature description and "caveats". I'd split the paragraph named "Addons, Collaborators and Environment Variables" in two, and extract the important info into a "Security Considerations" paragraph

**Comment by guillaume-sc** [comment]
> I'd prefer a clear separation between feature description and "caveats". I'd split the paragraph named "Addons, Collaborators and Environment Variables" in two, and extract the important info into a "Security Considerations" paragraph

Indeed, I like this approach. I suggest we push the initial change of @cyrille-sg, and I'll liaise with him to decide whether he, or I, go the extra mile with what you describe above.

**Comment by guillaume-sc** [comment]
With the release of the enhanced review apps feature, and its documentation, this is no longer needed.
