### ISSUE TITLE
Security Bulletins pages are not properly readable on mobile

### ISSUE THREAD

**Issue by yanjost** [Scalingo/documentation#1917]
See [ITT-291]

Example page  : https://doc.scalingo.com/security/bulletins/ssb-2023-001

[ITT-291]: https://scalingo.atlassian.net/browse/ITT-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ksol** [comment]
Firefox adaptive view gives a correct result, same for safari iOS (iphone mini 12).

I can confirm that I get the same screenshot as you with chrome adaptive view, but that's as far as I can go. A friend of mine had the issue on android so I'm going to suppose it's chrome specific

**Comment by cyrille-sg** [comment]
What is happening: Chrome does not want to break urls into multilines, and no css (that I found so far) will make it do that. Consequently, it is breaking the design that was based on the assumption that long words in generals, so urls too, will be broke into multiples parts when needed.

![Image](https://user-images.githubusercontent.com/62012562/220308812-78f3840e-b9b6-4eb8-8038-46dfe487a568.png)

The solution: Do not use long unbreakable urls

So no:

```
- GitHub: [https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests)
- Gitlab: [https://docs.gitlab.com/ee/user/project/merge_requests/#view-merge-requests](https://docs.gitlab.com/ee/user/project/merge_requests/#view-merge-requests)
```
But instead
```
- [GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests)
- [Gitlab](https://docs.gitlab.com/ee/user/project/merge_requests/#view-merge-requests)
```
Or even
```
 - [A very long text that said something about this url but it not a url so, constitutionnellement, breakable by chrome](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests)
```

**Comment by cyrille-sg** [comment]
PR has been done to fix the issue in this bulletin

**Comment by ksol** [comment]
>  Chrome does not want to break urls into multilines

uh, weird! what's the source for that ?
