### ISSUE TITLE
Add an anchor link to section

### ISSUE THREAD

**Issue by yohann-bacha** [Scalingo/documentation#1965]
For our documentations, we should copy links to sections more easily.

`id` element is already present, but no convenient way to easily copy the link to a section.

**Comment by EtienneM** [comment]
![2023-08-28_17-17](https://github.com/Scalingo/documentation/assets/1567651/16500792-b2a6-4ca2-a9d4-76c3bfc46190)

It is possible to get the link to a section by clicking on its title on the right block. Isn't it enough @yohann-bacha?

**Comment by yohann-bacha** [comment]
I actually saw this after I created this issue.. even if this is not the most intuitive, I am totally okay that this is enough, you can close this
