### ISSUE TITLE
Password with GitHub login

### ISSUE THREAD

**Issue by Anouchka-M** [Scalingo/documentation#1976]
Related to this conversation : 
https://scalingo.slack.com/archives/C03T384J3/p1676988428291169

It would be nice to add information about how and why to add a password with GitHub login.
In some cases, a client using his GitHub login needs to add a password (login with the CLI, activating Two-factor authentication and maybe other cases) but the "normal" behaviour of the platform in this case isn't explained.

Is the field asking for the previous password present or not ? 
If yes, should the user just click in it to activate it, or ignore it ?

It happened that a client doesn't remember if he added a password in the past, and without knowledge of the "normal" behaviour, he didn't know if he needed to set or reset his password.

**Comment by baptmaury** [comment]
@Anouchka-M do you remember what should do the user in this case ? Because he need an old password to set a new one

**Comment by Anouchka-M** [comment]
@baptmaury I think he just needs to reset password and it'll ask him to create one?
Ask lvl3 or Brandon to be sure.

**Comment by EtienneM** [comment]
I confirm that customers need to use the "Forgot my password" form in case they created their Scalingo account using GitHub account.

**Comment by baptmaury** [comment]
I'm a bit worried about this issue, I'm trying to find a way to put this info in the documentation, but haven't found anything good from my point of view. Any idea ?
