### ISSUE TITLE
Duplication of links in folder index

### ISSUE THREAD

**Issue by btrd** [Scalingo/documentation#1980]
On those pages links are duplicated

https://doc.scalingo.com/security
https://doc.scalingo.com/databases
https://doc.scalingo.com/languages.

![Screenshot from 2023-02-22 17-17-30](https://user-images.githubusercontent.com/1385737/220707639-39163c39-e4e3-49e9-85cd-b7e013a3cb1c.png)

**Comment by cyrille-sg** [comment]
Took a 30 min look, but did not understood how it was generated - I will wait Jean input next week
