### ISSUE TITLE
[Node.js] Document how to configure NPM config behavior

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/documentation#1981]
We are forking the Node.js buildpack from Heroku. In the Heroku documentation there is this piece of doc: https://devcenter.heroku.com/articles/nodejs-support#configuring-npm

It could be nice to have it to in our documentation too.

For example a customer that want to use the following command `npm ci --legacy-peer-deps` instead of our `npm ci` in the buildpack, they can change the behavior of NPM by:
- Adding a `.npmrc` file with `legacy-peer-deps=true`
- Or by setting the following env variable: `NPM_CONFIG_LEGACY_PEER_DEPS` to `true`

It could be nice to document the same thing as Heroku and show the example with legacy peer deps.

We are telling a bit of that in the README of the buildpack: https://github.com/Scalingo/nodejs-buildpack#configure-npm-with-npmrc but that's not sufficient.

**Comment by baptmaury** [comment]
There is no mention anymore of `legacy-peer-deps`. I created a PR based on the heroku documentation
