### ISSUE TITLE
[GitLab CI with DPL] Job marked as OK instead of failure

### ISSUE THREAD

**Issue by jpolo** [Scalingo/documentation#1987]
I followed the documentation to integrate Scalingo within Gitlab CI (using dpl).

The main problem of this tool seems to be that when an error is triggered during the build (ex: buildpack job failed) the job is considered as OK, which is ... dangerous.

When browsing dpl repository, it is not clear if the project is actively maintained (everything is alpha supported, since more than 6 months, low activity on repo).

A a Scalingo customer, I would see no objection of removing dpl if considered as a deprecated way of deploying. But ideally, scalingo would provide a clear and simple way to use scalingo CLI in gitlab runner environment...
Or Scalingo could provide support for dpl to ensure everything is working fine.

Thanks in advance !

Example of log :
```shell
!     An error occurred during buildpack compilation
 !   Error deploying the application
!   → Invalid return code from buildpack
To ssh.osc-fr1.scalingo.com:vera-production.git
   21620e6..b8e69ea  HEAD -> master
$ timeout 60 ./scalingo keys-remove dpl_tmp_key
Key 'dpl_tmp_key' has been deleted.
Cleaning up project directory and file based variables
00:00
Job succeeded
```

**Comment by brandon-welsch** [comment]
Hi, i'm Software Engineer at Scalingo.

Scalingo already provides support for DPL, but the DPL maintainers did not accepted our several PRs for quite some time ago.

For the moment DPL remains documented as it is now, but this will probably change in the future as DPL seems to be stale 😕.

But thank you for reporting this 🙏🏻
