### ISSUE TITLE
The Django docs recommends an obsolete dependency

### ISSUE THREAD

**Issue by stephane** [Scalingo/documentation#2069]
https://doc.scalingo.com/languages/python/django/start

The meta package `django-toolbelt` is outdated for many years now (https://pypi.org/project/django-toolbelt/).
I think you should replace it by:
- django
- psycogp2 (Django <4.2) or psycopg[binary] (Django 4.2+)
- gunicorn
- dj-database-url
- whitenoise (instead of dj-static)

**Comment by yohann-bacha** [comment]
Didn't have time to fully fix the docs, but here are some research I made:

First, we should first create a requirements.txt containing the content of the deprecated library: 

django
psycopg2
gunicorn
dj-database-url

But not dj-static, as it is unmaintained.

An alternative is [whitenoise](https://whitenoise.readthedocs.io/en/latest/), which is configurable for serving static files, and well integrated with Django, and production ready.
