### ISSUE TITLE
the .html is required

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#215]
The .html part of the url is now required this is a breaking change and has impact on some links in our blog:
Work:  https://doc.scalingo.com/internals/x-request-id.html
Do not:https://doc.scalingo.com/internals/x-request-id

See https://scalingo.com/articles/2017/06/13/http2-new-routing-features.html

**Comment by yannski** [comment]
Since doc redesign, all URLs ends without .html
