### ISSUE TITLE
Add plausible.io

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/documentation#2353]
Add plausible analytics.
This is a code issue of the documentation project, and not a documentation issue.

Plausible is an privacy oriented analytic solution https://plausible.io. Then the goal will be to remove Google analytics.
This change will affects all pages.

Asked internally under `New Analytics Stack` project.

**Comment by EtienneM** [comment]
The description of this issue is a bit sparse. What kind of information should be added? What is this tool? In which section/page should something be added?
