### ISSUE TITLE
[PHP] update introduction page

### ISSUE THREAD

**Issue by ipfaze** [Scalingo/documentation#2378]
The following page need a bit of update/cleaning because some deprecated things are mentioned such as CackePHP, etc.
https://doc.scalingo.com/languages/php/start

**Comment by Frzk** [comment]
| Framework | Version | Status | Link | Notes |
| --------- | ------: | ------ | ---- | ----- |
| CakePHP | `5` | OK | https://fku-cakephp.osc-fr1.scalingo.io/ | Requires PHP >= 8.2 |
| CodeIgniter | `4` | OK | https://fku-codeigniter.osc-fr1.scalingo.io/ | Requires PHP >= 8.0 |
| Symfony | `7` | To-do | | |
| Laravel | `10` | To-do | | |
| Laravel Lumen | `10` | To-do | | |
| Slim  | `4` | To-do | | |
| Magento  | `2` | To-do | | |
| Laminas MVC | `3` | To-do | | former Zend Framework |
| Silex  | | Deprecated | | Remove from doc |

**Comment by Frzk** [comment]
We should also rename "legacy" to "classic".
