### ISSUE TITLE
[STORY-228] Document procedure to create Primary Keys and change db engine to innoDB

### ISSUE THREAD

**Issue by ipfaze** [Scalingo/documentation#2414]
[STORY-228](https://notion.so/STORY-228)

For the migration of MySQL 5.7 to 8.x, we need to document an SQL Procedure to ease it for our customer.
In this procedure, we need to check if all tables check requirements for MySQL 8:
- [ ]  All tables must have `Primary Keys`
- [ ] All tables must use `InnoDB` engine

@curzolapierre already started this work and comment it here: https://github.com/Scalingo/appsdeck-database/issues/3035#issuecomment-1845049509
It handles the `Primary Keys` part but not the `InnoDB` engine yet.

**Comment by yohann-bacha** [comment]
For those two points, I struggle to understand what we should add to what we already have in the doc ? https://doc.scalingo.com/databases/mysql/mysql-8-prerequisites

**Comment by ipfaze** [comment]
@yohann-bacha To ease this process, we want to propose our customer a "one copy/paste" SQL procedure.
Pierre started to work on it here: https://github.com/Scalingo/appsdeck-database/issues/3035#issuecomment-1845049509
But it misses the InnoDB part.

**Comment by yohann-bacha** [comment]
Assigning @curzolapierre as he said he will soon take care of it
