### ISSUE TITLE
Block to install the CLI in header of some page

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#244]
Heroku has such block at the beginning of some pages:

![screenshot-2018-2-23 getting started on heroku with go heroku dev center](https://user-images.githubusercontent.com/1567651/36588422-51f3148a-1888-11e8-9f35-c781624676fa.png)

You can download the CLI right from there!

**Comment by Soulou** [comment]
Don't we have this now? @EtienneM

**Comment by EtienneM** [comment]
Yep
