### ISSUE TITLE
Review apps: discourage adding secrets ENV in scalingo.json

### ISSUE THREAD

**Issue by aurelien-reeves-scalingo** [Scalingo/documentation#2521]
[That chapter on its own](https://doc.scalingo.com/platform/app/review-apps#addons-collaborators-and-environment-variables) seems to advise users to add secrets ENV in their scalingo.json, which is actually a bad practice (it would result into having secrets into the repository)

There is a whole chapter later about that issue: https://doc.scalingo.com/platform/app/review-apps#configuration-of-review-apps

It could be nice in the chapter about ENV customization to have  disclaimer and a link to the later chapter

**Comment by EtienneM** [comment]
> That chapter on its own seems to advise users to add secrets ENV in their scalingo.json

I don't see where it is advise to add a secret in the scalingo.json. Could you copy-paste the text encouraging this?

**Comment by aurelien-reeves-scalingo** [comment]
I missed to add a link indeed

https://doc.scalingo.com/platform/app/review-apps#addons-collaborators-and-environment-variables

> If you’ve enabled review apps, a new application will be created every time a new PR is opened in your linked SCM-hosted repository. This new application is a child application.
> 
> Child applications clone some information from the parent app:
> 
>     the [environment variables](https://doc.scalingo.com/platform/app/environment) (can be overridden in scalingo.json)
> 

This is not directly recommending to add secret in scalingo.json, but reading this as-is may lead into thinking that it is the way to go to customize the ENV, the ENV being the place to store secrets. Thus the shortcut is: "in order to customize the ENV of a review app, I have to put those value in scalingo.json"

**Comment by EtienneM** [comment]
Thanks for the clarification :+1:
