### ISSUE TITLE
The left menu goes up after scrollingdown a little bit

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#253]
On https://documentation-service-pr233.scalingo.io/languages/haskell/start:

![screenshot-2018-3-8 haskell](https://user-images.githubusercontent.com/1567651/37141297-d6ec6066-22b4-11e8-8186-9966055bc766.png)

**Comment by yannski** [comment]
How can I reproduce?

**Comment by yannski** [comment]
OK, found: very big screen resolution
