### ISSUE TITLE
Rename "Addons" to "Addons / Databases"

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#254]
So that the word "Databases" is at the top level.

**Comment by yannski** [comment]
If we wanted to be consistent with this, it should be done accross all Scalingo's websites (homepage, dashboard, etc). Therefore, I'm not in favor to this.

**Comment by Soulou** [comment]
I agree with the consistency argument, but is it something we want to do? (Exposing more the `Databases` word)

**Comment by EtienneM** [comment]
OK I understand. But if I try to have the mind of someone new to Scalingo, and maybe new to PaaS. If I go to the documentation, with the current naming, I am not sure that I would understand that PostgreSQL is an addon.

**Comment by yannski** [comment]
That's a broad discussion that cannot not be resolved in one single repo.
