### ISSUE TITLE
If there is only one sub-entry, remove the sub-entry and make the parent clickable

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#255]
For instance, in the following page:
![screenshot-2018-3-8 haskell](https://user-images.githubusercontent.com/1567651/37141448-4573e86a-22b5-11e8-8bb3-eeb5691b062f.png)

Haskell only has an "Introduction" sub-entry. It would be nice to automatically remove the sub-entry and make the word "Haskell" clickable so that it shows this "Introduction" page.

**Comment by yannski** [comment]
I'm not in favor to this. I prefer the "scheme" to be concistent accross all languages (same for add-ons)

**Comment by EtienneM** [comment]
If I click on "Haskell" and see only a single element, it feels really empty... :s
Not sure it is mandatory to stay consistent here. If we remove the "Introduction" sub-entry and remove the arrow near the Haskell word, I think it's rather clear that it will be a link to a page instead of opening a menu.

**Comment by yannski** [comment]
all things considered, it would have been the nature thing we would have done in the first place. I'll rename the pages.

**Comment by yannski** [comment]
Won't do that
