### ISSUE TITLE
[Javascript] devDependencies documentation is incorrect, they are now installed by default

### ISSUE THREAD

**Issue by leo-scalingo** [Scalingo/documentation#2645]
Our nodejs-buildpack and our NodeJS documentation https://doc.scalingo.com/languages/nodejs/start#install-devdependencies

It seems our documentation does not match reality on the handling of devDependencies.
The buildpack behaviour has changed, devDependencies are always installed, then they are pruned at the end of the build (so only production dependencies are left during the runtime)

Our documentation states the opposite and should be updated.

**Comment by Chanizo** [comment]
Hi, we have a problem related to this new behaviour. In our project, Cypress is installed as dev dependencies, and by default it installs needed binaries in global system cache (~/.cache/Cypress) folder to share it between different projects. It seems that 'npm prune' does not remove it. Consequently our image build size is big...

**Comment by EtienneM** [comment]
Hi @Chanizo,

Can you please contact our support team to get help about your issue? There is an embedded chat on the web dashboard to contact them. Or you can send an email to support@scalingo.com.
