### ISSUE TITLE
Add all details about how to stop free trial period

### ISSUE THREAD

**Issue by curzolapierre** [Scalingo/documentation#2716]
Following this PR: https://github.com/Scalingo/documentation/pull/2438

We should also add information on how to stop the free trial period.
e.g. go to `/billing` => use `Stop free trial` button.

**Comment by EtienneM** [comment]
@curzolapierre I'm not sure I understand what you mean. In the PR #2438, I can see:

> To leave free trial period with billing profile go to [Billing](https://dashboard.scalingo.com/billing) and click on Stop free trial button.

Don't you think it's enough?
