### ISSUE TITLE
[PostgreSQL] Document how to restore locally a backup from a Scalingo-hosted database

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#2749]
A customer mentioned  this missing part on our documentation: https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700320073#part_id=comment-12375700320073-21909755017

Explanation from the customer:

Pour pouvoir restorer :
1) télécharger un backup
2) tar -xf <nom_fichier>.tar.gz
3) pg_restore --username=dev -d principale --clean --no-owner --jobs=6 /path/to/<nom_fichier>.pgsql

j'ai essayé différentes combinaisons avec pg_restore (mais c'est un outil que je connais peu, donc j'ai pu rater des choses) et je n'ai pas réussi à restore à partir du .gz directement
d'où le tar -xf

Aussi, ma bdd est configurée avec un autre username, donc j'ai du utiliser --no-owner pour éviter les messages d'erreur relatifs au fait que l'utilisateur utilisé sur Scalingo n'existe pas

**Comment by sc-zenokerr** [comment]
Our current documentation does mention the tar command and the --no-owner flag. The steps to use these when restoring a database locally are trivial.
