### ISSUE TITLE
The different swapping patterns should be explained (lack of memory/unused memory)

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#277]

**Comment by EtienneM** [comment]
Done here: https://doc.scalingo.com/platform/app/metrics#container-charts:

> The swap usage can increase in two different situations:
    - the application uses all the available memory usage. The system starts using the swap to allocate new memory block.
    - if some memory blocks are are never accessed during a long period of time, the kernel moves them to the swap, waiting for the next usage. At the first read of these blocks, the kernel moves them back to the main memory. Hence, just the first read is impacted in terms of performance. The impact on the performance is different than the previous case where the swap until enough memory is available.

**Comment by Soulou** [comment]
Fixed by #335
