### ISSUE TITLE
[DB] Changing Plans

### ISSUE THREAD

**Issue by Frzk** [Scalingo/documentation#2842]
Seems like there are cases that are not covered by our documentation. This needs to be fixed.
See https://scalingo.slack.com/archives/CRC7L0XM2/p1728638539501949 for further details.

**Comment by EtienneM** [comment]
@Frzk this issue really lacks information. The Slack thread is too messy to add valuable information. Could you write here what needs to be fixed in our documentation?

**Comment by Frzk** [comment]
Goal is to explain the downtime when switching plans:
- from Starter to Starter
- from Starter to Business
- from Business to Business
- from Business to Starter

I'm on it :)
