### ISSUE TITLE
[nginx] list of versions is too big

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#2865]
![image](https://github.com/user-attachments/assets/97ae32c4-dc23-413d-bdc7-7294e5c702f8)

_from https://doc.scalingo.com/platform/deployment/buildpacks/nginx#specify-nginx-version_

IMO we should only highlight the versions that are still officially supported.

In the case of Nginx, I think it should only be the LTS, hence it is only 1.26.

What do you think @Frzk ?

**Comment by Frzk** [comment]
I think we could keep both the stable (`1.26.x`) and mainline (`1.27.y`) versions, as we follow and maintain them. Would that be ok for you @EtienneM ?

**Comment by EtienneM** [comment]
Yes LGTM :)
