### ISSUE TITLE
Add information on archive's size during deployement

### ISSUE THREAD

**Issue by mickael-plassard** [Scalingo/documentation#2904]
Hey there, 

In our documentation [here](https://doc.scalingo.com/platform/getting-started/common-deployment-errors#image-too-large), we speak about the size error customers encounter when they hit the maximal size of an application image (1.5 GiB). 

However, users hit another size related error regarding the "max_archive_size" that is not documented in our guide. This is the other error:
- Fail to fetch source code: fail to handle tgz: The archive is too heavy (more than 314572800 bytes)

Do you think it is possible to add that archive size limit in our documentation of common deployement errors? We have more information about this internally in our Notion page "Application limits" >> "max_archive_size".

This customer came to Support to ask for more information about this as he could not find it in our guide. 

[Intercom ticket ](https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700346509?view=List)

Thanks for your help in advance.

**Comment by sc-zenokerr** [comment]
Fixed in linked PR #2910
