### ISSUE TITLE
MySQL type of licence used

### ISSUE THREAD

**Issue by mickael-plassard** [Scalingo/documentation#2908]
Hey there, 

Would it be possible to add the type of licences (community) we use for MySQL as customers comes in Support asking for that information?
I believe it would be suitable in this guide article: [Scalingo for MySQL® Overview](https://doc.scalingo.com/databases/mysql/overview)

[Intercom conversation](https://app.intercom.com/a/inbox/w4oogu7s/inbox/admin/7915327/conversation/12375700346688?view=List)

Thanks for your help as always.

**Comment by sc-zenokerr** [comment]
Fixed in the linked PR #2909
