### ISSUE TITLE
Integrate CLI documentation

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#34]
cli.scalingo.com should be more minimalistic

**Comment by Zyko0** [comment]
Do you mean that we should cut colored-blocks 1 (Features) & 2 (Configuration) from the page to move them to doc.scalingo.com?
So that cli.scalingo.com is a release page, showing only changelog and download link.

**Comment by yannski** [comment]
exactly yes

**Comment by yannski** [comment]
See http://doc.scalingo.com/app/command-line-tool.html
