### ISSUE TITLE
Add page about the log drain feature

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#356]
With a warning at the beginning stating it's a beta feature

**Comment by yannski** [comment]
Is it an addon?

**Comment by EtienneM** [comment]
We have to decide about that. For now, we do that for free. It could be a simple settings for the app.

**Comment by Soulou** [comment]
I'm not sure that an addon the the best method to actually present this feature to the user. It could be 'Logentries Integration" or "Syslog Drains" or something like this.

The quickest workflow would be:

1. Go on Logs Integrations on the dashbaord
2. Copy / Paste the Logentries URL
3. Click on Save

With an addon, it more cumbersome

1. Go on the app dashboard, addon tabs
2. Open the plan selection form
3. Choose the plan
4. Wait provisioning
5. Click on "go to dashboard" (requirement of external dashboard?)
6. Copy/paste the value
7. Confirm
