### ISSUE TITLE
In postdeploy hook, explain the difference with the Heroku "release"

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#379]

**Comment by EtienneM** [comment]
Here is Heroku's doc about its release phase (https://devcenter.heroku.com/articles/release-phase). I don't really see the difference with our postdeploy phase.

@yannski can you elaborate on this?

**Comment by ksol** [comment]
@yannski up please, otherwise this will get closed

**Comment by yannski** [comment]
there are differences. Otherwise we would have use the same "release" name. At least, "release" is a couple of "build" + "set of env vars"

**Comment by Soulou** [comment]
* Scalingo postdeploy is run synchronously at the end of each deployment
* Heroku release is run after each new release of the code:
  * New deployment
  * Change of environment variable
  * Promotion in Heroku pipeline from staging to production
