### ISSUE TITLE
[Search] Typing `install scalingo cli` provides incorrect result

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#419]
When typing `install scalingo cli` in the search bar. The only result we have is:
https://doc.scalingo.com/platform/deployment/deploy-java-jar-war#install-scalingo-cli

Instead of:
https://doc.scalingo.com/platform/cli/start

**Comment by ksol** [comment]
Still true.

**Comment by Soulou** [comment]
It's SEO issue on https://doc.scalingo.com/cli, it should include the keywords a user would use to find/install the CLI

**Comment by yannski** [comment]
Or maybe even https://doc.scalingo.com/platform/cli/start

**Comment by EtienneM** [comment]
This is now fixed by #958, #960 and aa73088! :)
