### ISSUE TITLE
Documentation page about using pipenv (with Pipfile) to handle python dependencies

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#443]

**Comment by EtienneM** [comment]
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/search/conversations/19047761914?q=pipfile

**Comment by EtienneM** [comment]
We introduced in #406  on July the 30th a paragraph about pipenv in the start page. Did you had anything else in mind for this issue @Soulou ?

**Comment by EtienneM** [comment]
This page (https://doc.scalingo.com/languages/python/start#recommended-pipenv) talks about pipenv
