### ISSUE TITLE
[changelog] Entries from homepage 'recently modified' are targeting full page of changelog not anchor

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#448]
It messes up the search

**Comment by EtienneM** [comment]
I don't really understand this one, can you explain a bit more?

**Comment by Soulou** [comment]
When you're on the root of the documentation, in the recently modified part, you've entries of the changelog.

Instead of targeting /changelog#title

They go to a full page for the entry, /changelog/title

Which is not the expecting behavior, as it messes with the search.

**Comment by EtienneM** [comment]
I don't know how we could do that as this block includes both changelog entries and doc pages. The provided link is fine for the doc pages but not for the changelog entries.. Maybe @yannski who played with Jekyll has an idea?

**Comment by EtienneM** [comment]
It's OK, I found a way.
