### ISSUE TITLE
[DNS] Setup instructions

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#459]
Add some instructions on how to setup a domain name on major providers. With and without wildcard.

**Comment by Soulou** [comment]
@johnsudaar what would you change from here: https://doc.scalingo.com/platform/app/domain#wildcard-domain ? (most is already detailed)

**Comment by EtienneM** [comment]
ping @johnsudaar

**Comment by EtienneM** [comment]
Closing as we lack too much information about what is missing
