### ISSUE TITLE
Rewrite the "Wordpress" page to integrate good practices

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#469]
And mention https://github.com/Scalingo/scalingo-wordpress

**Comment by EtienneM** [comment]
@yannski Can you elaborate a bit? What do you call "good practice" in this case? Just mentioning https://github.com/Scalingo/scalingo-wordpress or is there more?

**Comment by Soulou** [comment]
I think we should speak of bedrock and of our distribution of wordpress in the first paragraph of this page.

All the things related to configuration are done automatically with bedrock and are only needed for "manual" style wordpress we should advise against.

It should be more "How to deploy a wordpress on Scalingo" "To do it, take our bedrock, it will work out of the box"

**Comment by EtienneM** [comment]
Actually I don't really get what https://github.com/Scalingo/scalingo-wordpress is doing. Isn't Bedrock the way to go to deploy on Scalingo?

**Comment by Soulou** [comment]
The repository is a bedrock preinstalled configured for one-click deploy, with by default the S3 plugin for the uploads
