### ISSUE TITLE
Let's Encrypt certificate statuses are no longer valid

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#513]
http://172.17.0.1:4300/platform/app/ssl#lets-encrypt-certificate-statuses

@Soulou Can you confirm some of these states no longer exist?

**Comment by Soulou** [comment]
Theses states? Which one? https://doc.scalingo.com/platform/app/ssl#lets-encrypt-certificate-statuses those still exist

**Comment by EtienneM** [comment]
"Pending DNS" still exists? OK sorry...
