### ISSUE TITLE
[Suggestion] Custom buildpack page should present a very simple example

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#538]

**Comment by johnsudaar** [comment]
Like this one: https://doc.scalingo.com/platform/deployment/buildpacks/custom#build-a-custom-buildpack

**Comment by EtienneM** [comment]
Ping @yannski :arrow_up: Did you have anything else in mind than the current doc?

**Comment by yannski** [comment]
Fixed in 219ee090bbd193235655d70115a93e1446b11aa8
