### ISSUE TITLE
There should be a page dealing with 'unknown technology message'

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#58]
When detection fails to be detected, the following message is displayed:

```
<-- Start deployment of [app] -->
 !     We didn't find the type of technology your are using...
       We're sorry this build is failing!
       If you can't find the issue in your application code,
       please send us an email at support@scalingo.com

       <3,
       Scalingo
 !   Error deploying the application
 !   → Invalid return code from buildpack
```

There should be a documentation page refering this message and explaining what to do
- Go to the page of the good language to see how we detect it
- Use PROJECT_DIR environment variable (see doc) if the project is not at the root of the GIT repository

**Comment by Soulou** [comment]
Please send the link to the page in this issue when done

**Comment by yannski** [comment]
The page should be a condensate of all the other pages.

**Comment by Soulou** [comment]
PROJECT_DIR page -> http://doc.scalingo.com/deployment/project-dir.html

**Comment by yannski** [comment]
Page exists here https://doc.scalingo.com/platform/deployment/unknown-technology
