### ISSUE TITLE
[UI] Sidebar nav length is sometimes wrong at first time load

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#583]
![Screenshot_2019-06-03 Router Error Codes](https://user-images.githubusercontent.com/11287/58806068-a60fcf80-8615-11e9-9be9-70a3db83809b.png)

**Comment by EtienneM** [comment]
It seems to be fixed, I failed to reproduce on the same page: https://doc.scalingo.com/platform/internals/router-error-codes
