### ISSUE TITLE
"continuous integration" does not exist in the doc

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#601]

**Comment by ksol** [comment]
When I search for it there's a few results, including the one about SCM integrations and deployments. Is it not what is wanted ?

**Comment by Soulou** [comment]
There should be a page about Continous Integration in general, listing all the specialized pages we already have (ie. https://doc.scalingo.com/platform/deployment/deploy-scalingo-from-travis-ci#top-of-page)

This page should also refer to how our SCM integrations are working
