### ISSUE TITLE
Guide to use MongoDB with MongoChef

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#62]
- Setup Tunnel
- Use the 'To URI' dialog to connect to 

```
mongodb://user:pass@localhost:port-of-tunnel/dbname
```

**Comment by yannski** [comment]
Provide your screenshots please

**Comment by Hamatek** [comment]
thanks works great

**Comment by EtienneM** [comment]
Done: http://doc.scalingo.com/databases/access-database.html#connect-your-workstation-to-the-database
