### ISSUE TITLE
Development preferred workflow for multi stage environment

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#64]
Page is missing.

An example with staging and production environments should be given as well.

**Comment by EtienneM** [comment]
@yannski What did you mean here? Like explaining the GitHub workflow we currently use (with `master` and `prod` branch)?

**Comment by yannski** [comment]
Yep and branch management. With and without GH integration. Maybe extend to review apps.

**Comment by EtienneM** [comment]
I think this page (https://doc.scalingo.com/platform/app/scm-integration) solves this issue. Feel free to re-open with more details if you don't think so.
