### ISSUE TITLE
Update Ruby on Rails logging recommendations

### ISSUE THREAD

**Issue by archiloque** [Scalingo/documentation#664]
the [Ruby on Rails page](https://doc.scalingo.com/languages/ruby/rails/start) recommend using the rails_12factor gem to get the rails_stdout_logging gem for STDOUT logging

- it seems the rails_12factor and rails_stdout_logging gems are not maintained anymore
- rails 5 added an environment variable to enable STDOUT logging https://github.com/rails/rails/pull/23734 so the gem is not required

Thanks

**Comment by Soulou** [comment]
Hi there, right the documentation is obsolete here. What was done by those two gems is now done automatically.

Our buildpack is injecting the right environment variable automatically, see 

https://github.com/Scalingo/ruby-buildpack/blob/master/lib/language_pack/rails5.rb#L20

I'll update the documentation and close this issue once done. Thanks @archiloque for the heads up.

**Comment by Soulou** [comment]
Fixed by https://github.com/Scalingo/documentation/commit/2d995d3e4e0e6a6b214efe9f672ab5bc9568597e
