### ISSUE TITLE
Search input is ugly dans borked on some browsers

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#73]
![scalingo_-_documentation_center_-_2015-12-01_22 06 04](https://cloud.githubusercontent.com/assets/11287/11514245/bdfcacd8-9877-11e5-9fcb-9dab2c7dfc8b.png)
<img width="1280" alt="capture 20d ecran 202015-12-01 20a 2021 52 48" src="https://cloud.githubusercontent.com/assets/11287/11514267/dbcdf6f4-9877-11e5-998c-4a6ec2c9d248.png">

**Comment by yannski** [comment]
When done, respond to https://app.intercom.io/a/apps/w4oogu7s/inbox/conversation/1484157009?nsrc=slack

**Comment by Zyko0** [comment]
https://github.com/Scalingo/documentation/commit/274e17285ba530a4f6e03c1e40c5f20e2818ab1f
