### ISSUE TITLE
Remove https redirection nginx page ?

### ISSUE THREAD

**Issue by tyx** [Scalingo/documentation#732]
Hello !

When I tried to force my app in https I was confused by this page :
https://doc.scalingo.com/languages/php/https-redirect#nginx-configuration

As I now discover where the "force https" feature was hidden in my backoffice, I wonder if this page stills needed. Nobody should use https redirection on this way now, no ?

**Comment by EtienneM** [comment]
You're right, this page seems to date back from when we didn't support force HTTPS directly from the web dashboard. I'll clean that.
