### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/documentation#739]
![Setup_Blackfire_Agent_on_Scalingo_-_Scalingo](https://user-images.githubusercontent.com/3317829/69239736-34afe300-0b9b-11ea-8c86-3f8cf8766e2b.png)
https://doc.scalingo.com/languages/php/blackfire#top-of-page

This seems to happen when the content height is lower than the navbar height.

**Comment by johnsudaar** [comment]
Contact https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24627380509 when done

**Comment by akaaljotsingh** [comment]
@johnsudaar Increase the height of section#top-of-page in CSS may resolve this.
section#top-of-page {
height: 80vh;
}
