### ISSUE TITLE
[CLI][Backups] Explain how to get the temporary URL to download a backup

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#806]
This is useful if one want to use a backup from a one-off:

https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/25423595300

Récupérez l'ID de votre addon :

```
scalingo -a my-app addons
```

Listez les backups de l'addon :

```
scalingo -a my-app backups --addon <ADDON ID>
```

C'est dans la partie suivante qu'on va utiliser notre outil en ligne de commande en mode debug. Nous allons lancer la commande de téléchargement du backup, mais qu'on pourra interrompre lorsque le texte Temporary URL to download backup is  est apparu. Vous pouvez l'interrompre avec le raccourci clavier CTRL + C :

```
DEBUG=1 scalingo -a my-app backups-download --addon <ADDON ID> --backup <BACKUP ID>
```

L'URL qui vous intéresse est celle donnée sur la ligne du texte Temporary URL to download backup is . Elle commence par : https://db-api.agora-fr1.scalingo.com/api/databases/ . Vous pouvez utiliser cette URL dans le one-off. Par exemple :

```
$ scalingo -a my-app run bash
-----> Connecting to container [one-off-7874]...  
-----> Process 'bash' is starting...  
 [...]
[09:32] Scalingo:my-app ~ $ wget --output-document=backup.tgz <TEMPORARY URL>
[09:32] Scalingo:my-app ~ $ tar xvfz backup.tgz

```

**Comment by EtienneM** [comment]
Should we really have a documentation page with this? It seems a bit hacky... but it's useful. I explain this last week on the support.

**Comment by btrd** [comment]
I think we should have documentation about this, we already have an article https://scalingo.com/blog/cli-release-1-10

**Comment by EtienneM** [comment]
Do you want to write it @btrd? 😄

**Comment by btrd** [comment]
Now it's on my todo list :)

**Comment by EtienneM** [comment]
It is now possible to download a backup in a one-off container with the following sequence of commands:

```
scalingo --app my-app run bash

[15:01][osc-fr1] Scalingo:biniou ~ $ install-scalingo-cli 
[15:01][osc-fr1] Scalingo:biniou ~ $ scalingo login
[15:01][osc-fr1] Scalingo:biniou ~ $ scalingo backups-download
```

I don't think it deserves a documentation page anymore
