### ISSUE TITLE
[GitLab CI] Deploy on Scalingo using .gitlab-ci.yml file

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#810]

**Comment by ksol** [comment]
I'm not sure what's the scope of this ticket, do you mind detailing?

**Comment by EtienneM** [comment]
I have unfortunately no idea what this is about... :disappointed: 

I searched on Slack and found this message talking about this issue which gives a bit more context: https://app.slack.com/client/T02BUKFDJ/CGS1DPCUD/thread/CGS1DPCUD-1579604029.006800

I opened this issue in reaction to a customer stating `impossibilité d'intégrer scalingo à la CI/CD gitlab en utilisant .gitlab-ci.yml`. I don't have any more information than that.

**Comment by ksol** [comment]
alright, so let's close it then
