### ISSUE TITLE
[App SSL] Better explanation about how to handle intermediate certificates

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#86]

**Comment by Soulou** [comment]
-----BEGIN CERTIFICATE-----
... ton certificat ...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
... certificat intermédiaire 1 ...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
... certificat intermédiaire 2 ...
-----END CERTIFICATE-----

**Comment by yannski** [comment]
See https://doc.scalingo.com/platform/app/ssl#how-to-upload-certificate-chains
