### ISSUE TITLE
[PHP Laravel] Document should be updated for Laravel 7

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#867]

**Comment by EtienneM** [comment]
Do you have more information about what should be changed to better suit changes introduced in Laravel 7?

**Comment by EtienneM** [comment]
Our sample (https://php-laravel.is-easy-on-scalingo.com/) is deployed using Laravel 9:

https://github.com/Scalingo/sample-php-laravel/blob/1ed43731f1e41637b6e257901df078d1cc9bdcc0/composer.json#L10

I don't see any major difference with the doc instructions. Hence I'm closing this issue.
