### ISSUE TITLE
[PHP Laravel] Driver errorlog should be used for logging

### ISSUE THREAD

**Issue by Soulou** [Scalingo/documentation#869]
https://laravel.com/docs/5.8/logging

**Comment by Soulou** [comment]
Env var `LOG_CHANNEL`

**Comment by EtienneM** [comment]
@Soulou The linked Laravel documentation page does not talk about the environment variable `LOG_CHANNEL`. Hence I'm not sure about what should be added in the documentation. Do you remember anything about this?

**Comment by EtienneM** [comment]
Please re-open if you remember what this issue is about.
