### ISSUE TITLE
Implement Basic Auth on Review Apps

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#878]
1. It leads to duplicate content which is bad for SEO
2. Some customers may be confused by reading documentation from review apps which may not be up-to-date

**Comment by Soulou** [comment]
It seems that some customers shared review app links in a support session, it's not normal they found it

**Comment by Soulou** [comment]
Probably it comes from the fact that the `documentation` repo is public on GitHub, so Google indexes it, including the commit status which contain the URLs of the review apps, leading to this situation.
