### ISSUE TITLE
[Databases] Backup Restauration only provides instruction for MongoDB

### ISSUE THREAD

**Issue by mackwic** [Scalingo/documentation#890]
We would need to add MySQL and PostgreSQL to the operations.

Source page: https://doc.scalingo.com/platform/databases/restore-backup

**Comment by EtienneM** [comment]
Actually, I think we should remove this page. We already have a "Dump & Restore" page for all DB type. For example:

- https://doc.scalingo.com/databases/postgresql/dump-restore
- https://doc.scalingo.com/databases/mysql/dump-restore

**Comment by yannski** [comment]
Yes, I really prefer specific database doc. It may lead to some duplicate content but user are searching documentation pages for *their* context

**Comment by mackwic** [comment]
or make an internal link ? I think this page is interesting for SEO.

Le jeu. 26 mars 2020 à 11:29, Étienne M. <notifications@github.com> a
écrit :
