### ISSUE TITLE
Flask documentation is not clear

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/documentation#897]
Better help user with following case:
- No need of celery
- Has already its code ready, just need the procfile configuration

Also, repair the sample 
```
-----> Installing SQLite3
mv: missing destination file operand after '/build/8cba8450-65e0-4e4d-8f64-035c5d9a83ab/.scalingo/python/include/'
Try 'mv --help' for more information.
mv: missing destination file operand after '/build/8cba8450-65e0-4e4d-8f64-035c5d9a83ab/.scalingo/python/lib/'
Try 'mv --help' for more information.
sed: can't read /build/8cba8450-65e0-4e4d-8f64-035c5d9a83ab/.scalingo/python/sqlite3/usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc: No such file or directory
mv: missing destination file operand after '/build/8cba8450-65e0-4e4d-8f64-035c5d9a83ab/.scalingo/python/bin/'
Try 'mv --help' for more information.
Sqlite3 successfully installed.
```

**Comment by EtienneM** [comment]
@cyrille-sg we wanted a comprehensive example, with various components. I think a user can infer from the various components what they need to apply to their application. For instance looking at the `Procfile` of the sample if they already  have a code base and just need to know how to boot it. Hence I would keep the documentation  that way. What do you think?

**Comment by cyrille-sg** [comment]
The initial message is so far away, and poorly written, that I am very unsure where was the problem and what was the proposed solution. If it survived three years without be closed, maybe it is not that important / obsolete. Fine to close it and keep the documentation that way
