### ISSUE TITLE
[Autoscaling] be more specific about thresholds

### ISSUE THREAD

**Issue by ksol** [Scalingo/documentation#908]
For instance, it's not clear if the mean of all containers must be above the threshold or if all of them must be.

**Comment by EtienneM** [comment]
We use the mean over the last 5 minutes

**Comment by ksol** [comment]
@EtienneM can I assign this to you until you double-check? I'll take care of actually updating the doc.

**Comment by EtienneM** [comment]
Clarification: 

If the alert is triggered for 2 consecutive minutes we trigger an autoscale. For these 2 minutes, we group the metric point by the minute. We have a mean for each minute. 

The code is kinda hard to read so I may be mistaken. But I would say that if the metric is CPU, RAM or Swap, if there are for instance multiple `web` containers, we take the average of all `web` containers.

Is that clear to you?

I don't know how to make that clear in the doc, I leave that to you ^^
