### ISSUE TITLE
Custom Error and Maintenance Pages is unclear about the purpose of the 4 environment variables

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/documentation#916]
https://doc.scalingo.com/platform/app/custom-error-page#custom-error-pages

    SCALINGO_STOPPED_PAGE_URL
    SCALINGO_NO_FRONT_ERROR_URL
    SCALINGO_APP_ERROR_URL
    SCALINGO_TIMEOUT_ERROR_URL

Especially, what is the difference between SCALINGO_STOPPED_PAGE_URL and SCALINGO_NO_FRONT_ERROR_URL

**Comment by Soulou** [comment]
Actually, if you're referring to the support ticket we had, when a user scales down their app, it's actualy SCALINGO_STOPPED_PAGE_URL, `NO_FRONT` is when only web containers are scaled down
