### ISSUE TITLE
[Elixir] Expand on how to configure

### ISSUE THREAD

**Issue by ksol** [Scalingo/documentation#941]
- Insist on the fact that the buildpack url is required
- Underline the importance `erlang_version` and `elixir_version` in the `elixir_buildpack.config`, the defaults in the buildpack are not up to date so filling those value may be required more often than not.

On a side-note: fork the buildpack and maintain our own "official" ?

**Comment by EtienneM** [comment]
> On a side-note: fork the buildpack and maintain our own "official" ?

yes Elixir is not officially supported. But as we added support for Erlang (:astonished: ) I think we should also fork this buildpack and start officially supporting Elixir. But I think the final decision is on @Soulou and @yannski. What do you think? :)

(and thanks for the sample!)

**Comment by yannski** [comment]
As Elixir is becoming popular among some of our customers (namely Dernier Cri and BetaGouv), I would vote +1 for official support of Elixir and Phoenix.
