### ISSUE TITLE
TLS paragraph in common Database page

### ISSUE THREAD

**Issue by yannski** [Scalingo/documentation#946]
Encryption at Rest is mentionned here:

https://doc.scalingo.com/platform/databases/intro

This page should also include a paragraph about TLS/Force TLS : our vision and the status for each database.

This page should also mention the Internet Accessibility feature and the default behavior.

**Comment by EtienneM** [comment]
@yannski Can you elaborate about what you mean with "our vision" of Force TLS?

**Comment by yannski** [comment]
@EtienneM What's your vision about TLS on database at Scalingo?

**Comment by EtienneM** [comment]
You can't answer a question with a question. You opened an issue and I ask you to clarify what you want. You can't answer with a question.

**Comment by yannski** [comment]
Let's put it another way. Can you describe how TLS is implemented on the database side ? Why ?

**Comment by EtienneM** [comment]
On the database side, there is a configuration file and we set the TLS configuration to on instead of off. And also we provide a certificate.
