### ISSUE TITLE
Move the wordpress documentation in the “Getting Started” category ?

### ISSUE THREAD

**Issue by mackwic** [Scalingo/documentation#983]
It feels like the Wordpress documentation is not purely a at his place in the PHP section. Also it makes it less discoverable for non-PHP people.

Maybe the “Getting started” section is a better place ?

**Comment by EtienneM** [comment]
Do you mean moving the content of this page (https://doc.scalingo.com/languages/php/wordpress) into the section "Getting Started" in a page called "Getting Started with WordPres on Scalingo"?

**Comment by mackwic** [comment]
Yes good reformulation ! :)
